#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".
#!/bin/sh
appname="cdonpass"
giturl=/tmpgit/cdonpass/.git
cause="Triggered+by+Git+Hook"

# Build jenkins URL

jenkinsJob="http://developer:developer@localhost:8999/job/Commit"
buildPath="/build?token=cdonpass"
echo "Notifying Jenkins of new push updates."
curl -v "${jenkinsJob}${buildPath}"

#Final step
exec git update-server-info
